NominaCRUD/Controllers/PagoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NominaCRUD.Models;

namespace NominaCRUD.Controllers
{
    public class PagoesController : Controller
    {
        private readonly RecorverNominaContext _context;

        public PagoesController(RecorverNominaContext context)
        {
            _context = context;
        }
        private void CalcularTotalesYNeto(Pago pago)
        {
            // Obtener las deducciones del empleado
            var deduccionesEmpleado = _context.DeduccionesEmpleados.Where(de => de.EmpleadoId == pago.EmpleadoId).ToList();
            decimal totalDeducciones = deduccionesEmpleado.Sum(de => de.Monto);

            // Obtener los ingresos del empleado
            var ingresosEmpleado = _context.IngresosEmpleados.Where(ie => ie.EmpleadoId == pago.EmpleadoId).ToList();
            decimal totalIngresos = ingresosEmpleado.Sum(ie => ie.Monto);

            // Obtener el salario base del empleado
            var empleado = _context.Empleados.FirstOrDefault(e => e.EmpleadoId == pago.EmpleadoId);
            decimal salarioBase = empleado.SalarioBase;

            // Calcular el salario neto
            decimal salarioNeto = salarioBase + totalIngresos - totalDeducciones;

            // Actualizar los campos en el objeto Pago
            pago.TotalDeducciones = totalDeducciones;
            pago.TotalIngresos = totalIngresos;
            pago.SalarioNeto = salarioNeto;
        }

       
        // GET: Pagoes
        public async Task<IActionResult> Index()
        {
            var recorverNominaContext = _context.Pagos.Include(p => p.Empleado);
            var ListaEmpleados = _context.Empleados;
            var LisIngresos = _context.IngresosEmpleados;
            var LisDeducciones = _context.DeduccionesEmpleados;

            var ListaIngresos = new List<IngresosEmpleado>();
            var ListaDeducciones = new List<DeduccionesEmpleado>();
            var ListaPagos = new List<Pago>();

            foreach (var item in LisIngresos)
            {
                ListaIngresos.Add(item);
            }

            foreach (var item in LisDeducciones)
            {
                ListaDeducciones.Add(item);
            }

            foreach (var item in ListaEmpleados)
            {
                decimal Deduccion = ListaDeducciones.Where(x => x.EmpleadoId == item.EmpleadoId).Sum(x => x.Monto);
                decimal Ingreso = ListaIngresos.Where(x => x.EmpleadoId == item.EmpleadoId).Sum(x => x.Monto);
                Empleado dataEmpleado = new Empleado()
                {
                    Nombre = item.Nombre
                };

                Pago NuevoPago = new Pago()
                {
                    EmpleadoId = item.EmpleadoId,
                    PagoId = 6,
                    TotalDeducciones = Deduccion,
                    TotalIngresos = Ingreso,
                    SalarioNeto = item.SalarioBase + Ingreso - Deduccion,
                    Empleado = dataEmpleado,
                    FechaPago = DateTime.Today

                };
                ListaPagos.Add(NuevoPago);
            }

            //return (IActionResult)(ListaPagos);
            return View(ListaPagos);
            //return View(await recorverNominaContext.ToListAsync());
        }

        // GET: Pagoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pago = await _context.Pagos
                .Include(p => p.Empleado)
                .FirstOrDefaultAsync(m => m.PagoId == id);
            if (pago == null)
            {
                return NotFound();
            }

            return View(pago);
        }

       
        // Acción para crear un nuevo pago
        public IActionResult Create(int? empleadoId)
        {
            if (empleadoId == null)
            {
                // Obtener la lista de empleados y sus datos
                var empleados = _context.Empleados.ToList();

                // Crear una lista de selección de empleados
                ViewData["EmpleadoId"] = new SelectList(empleados, "EmpleadoId", "Nombre");

                // Crear un objeto Pago para el formulario de creación
                var nuevoPago = new Pago();

                return View(nuevoPago);
            }
            else
            {
                // Obtener el empleado seleccionado
                var empleadoSeleccionado = _context.Empleados.FirstOrDefault(e => e.EmpleadoId == empleadoId);

                if (empleadoSeleccionado != null)
                {
                    // Crear un objeto Pago para el formulario de creación
                    var nuevoPago = new Pago { EmpleadoId = empleadoSeleccionado.EmpleadoId };

                    // Calcular los totales y el salario neto del empleado seleccionado
                    CalcularTotalesYNeto(nuevoPago);

                    // Asignar la lista de empleados y el empleado seleccionado para el campo de selección
                    ViewData["EmpleadoId"] = new SelectList(_context.Empleados.ToList(), "EmpleadoId", "Nombre", empleadoSeleccionado.EmpleadoId);

                    return View(nuevoPago);
                }
            }

            return NotFound();
        }




        // POST: Pagoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PagoId,EmpleadoId,TotalIngresos,TotalDeducciones,SalarioNeto,FechaPago")] Pago pago)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pago);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpleadoId"] = new SelectList(_context.Empleados, "EmpleadoId", "Nombre", pago.EmpleadoId);
            return View(pago);
        }

        // GET: Pagoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var pago = await _context.Pagos.FindAsync(id);

            if (pago != null)
            {
                return NotFound();
            }
            ViewData["EmpleadoId"] = new SelectList(_context.Empleados, "EmpleadoId", "Nombre", pago.EmpleadoId);
            return View(pago);
        }

        // POST: Pagoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PagoId,EmpleadoId,TotalIngresos,TotalDeducciones,SalarioNeto,FechaPago")] Pago pago)
        {
            if (id != pago.PagoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pago);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PagoExists(pago.PagoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpleadoId"] = new SelectList(_context.Empleados, "EmpleadoId", "Nombre", pago.EmpleadoId);
            return View(pago);
        }

        // GET: Pagoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pago = await _context.Pagos
                .Include(p => p.Empleado)
                .FirstOrDefaultAsync(m => m.PagoId == id);
            if (pago == null)
            {
                return NotFound();
            }

            return View(pago);
        }

        // POST: Pagoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pago = await _context.Pagos.FindAsync(id);
            if (pago != null)
            {
                _context.Pagos.Remove(pago);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PagoExists(int id)
        {
            return _context.Pagos.Any(e => e.PagoId == id);
        }
    }
}

NominaCRUD/Views/Pagoes/Create.cshtml
@model NominaCRUD.Models.Pago

@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>

<h4>Pago</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EmpleadoId" class="control-label"></label>
                <select asp-for="EmpleadoId" class ="form-control" asp-items="ViewBag.EmpleadoId"></select>
            </div>
            <div class="form-group">
                <label asp-for="TotalIngresos" class="control-label"></label>
                <input asp-for="TotalIngresos" class="form-control" />
                <span asp-validation-for="TotalIngresos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalDeducciones" class="control-label"></label>
                <input asp-for="TotalDeducciones" class="form-control" />
                <span asp-validation-for="TotalDeducciones" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SalarioNeto" class="control-label"></label>
                <input asp-for="SalarioNeto" class="form-control" />
                <span asp-validation-for="SalarioNeto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaPago" class="control-label"></label>
                <input asp-for="FechaPago" class="form-control" />
                <span asp-validation-for="FechaPago" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        // Este script se ejecutará cuando cambie la selección del empleado
        $('#EmpleadoId').change(function () {
            var selectedEmployeeId = $(this).val();
            window.location.href = '@Url.Action("Create", "Pagoes")?empleadoId=' + selectedEmployeeId;
        });
    </script>
}

NominaCRUD/Views/Pagoes/Delete.cshtml
@model NominaCRUD.Models.Pago

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>Seguro que desea eliminar esta informacion?</h3>
<div>
    <h4>Pago</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalIngresos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalIngresos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalDeducciones)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalDeducciones)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SalarioNeto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SalarioNeto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaPago)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaPago)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empleado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empleado.Nombre)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PagoId" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Volver a la lista</a>
    </form>
</div>

NominaCRUD/Views/Pagoes/Details.cshtml
@model NominaCRUD.Models.Pago

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    <h4>Pago</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalIngresos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalIngresos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalDeducciones)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalDeducciones)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SalarioNeto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SalarioNeto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaPago)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaPago)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empleado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empleado.Nombre)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.PagoId">Editar</a> |
    <a asp-action="Index">Volver a la lista</a>
</div>

NominaCRUD/Views/Pagoes/Edit.cshtml
@model NominaCRUD.Models.Pago

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Pago</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PagoId" />
            <div class="form-group">
                <label asp-for="EmpleadoId" class="control-label"></label>
                <select asp-for="EmpleadoId" class="form-control" asp-items="ViewBag.EmpleadoId"></select>
                <span asp-validation-for="EmpleadoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalIngresos" class="control-label"></label>
                <input asp-for="TotalIngresos" class="form-control" />
                <span asp-validation-for="TotalIngresos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalDeducciones" class="control-label"></label>
                <input asp-for="TotalDeducciones" class="form-control" />
                <span asp-validation-for="TotalDeducciones" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SalarioNeto" class="control-label"></label>
                <input asp-for="SalarioNeto" class="form-control" />
                <span asp-validation-for="SalarioNeto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaPago" class="control-label"></label>
                <input asp-for="FechaPago" class="form-control" />
                <span asp-validation-for="FechaPago" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NominaCRUD/Views/Pagoes/Index.cshtml
@model IEnumerable<NominaCRUD.Models.Pago>

@{
    ViewData["Title"] = "Index";
}

<h1>Pago</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TotalIngresos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalDeducciones)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SalarioNeto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaPago)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Empleado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TotalIngresos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalDeducciones)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SalarioNeto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaPago)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Empleado.Nombre)
            </td>
        </tr>
}
    </tbody>
</table>