NominaCRUD/Controllers/EmpleadoesController.cs
 using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NominaCRUD.Models;

namespace NominaCRUD.Controllers
{
    public class EmpleadoesController : Controller
    {
        private readonly RecorverNominaContext _context;

        public EmpleadoesController(RecorverNominaContext context)
        {
            _context = context;
        }

        // GET: Empleadoes

        public async Task<IActionResult> Index(string buscar)
        {
            var usuarios = from usuario in _context.Empleados select usuario;

            if (!String.IsNullOrEmpty(buscar))
            {
                usuarios = usuarios.Where(s => s.Nombre!.Contains(buscar));
            }

            return View(await usuarios.ToListAsync());

        }
        // GET: Empleadoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleados
                .FirstOrDefaultAsync(m => m.EmpleadoId == id);
            if (empleado == null)
            {
                return NotFound();
            }

            return View(empleado);
        }

        // GET: Empleadoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Empleadoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EmpleadoId,Nombre,Cedula,Codigo,Departamento,SalarioBase,FechaIngreso")] Empleado empleado)
        {           
            if (ModelState.IsValid)
            {
                _context.Add(empleado);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
           
            

            return View(empleado);
        }

        // GET: Empleadoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleados.FindAsync(id);
            if (empleado == null)
            {
                return NotFound();
            }
            return View(empleado);
        }

        // POST: Empleadoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EmpleadoId,Nombre,Cedula,Codigo,Departamento,SalarioBase,FechaIngreso")] Empleado empleado)
        {
            if (id != empleado.EmpleadoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(empleado);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmpleadoExists(empleado.EmpleadoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(empleado);
        }

        // GET: Empleadoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empleado = await _context.Empleados
                .FirstOrDefaultAsync(m => m.EmpleadoId == id);
            if (empleado == null)
            {
                return NotFound();
            }

            return View(empleado);
        }

        // POST: Empleadoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var empleado = await _context.Empleados.FindAsync(id);
            if (empleado != null)
            {
                _context.Empleados.Remove(empleado);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmpleadoExists(int id)
        {
            return _context.Empleados.Any(e => e.EmpleadoId == id);
        }
    }
}

NominaCRUD/Views/Empleadoes/Create.cshtml
@model NominaCRUD.Models.Empleado

@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>

<h4>Empleado</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cedula" class="control-label"></label>
                <input asp-for="Cedula" class="form-control" />
                <span asp-validation-for="Cedula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Codigo" class="control-label"></label>
                <input asp-for="Codigo" class="form-control" />
                <span asp-validation-for="Codigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Departamento" class="control-label"></label>
                <input asp-for="Departamento" class="form-control" />
                <span asp-validation-for="Departamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SalarioBase" class="control-label"></label>
                <input asp-for="SalarioBase" class="form-control" />
                <span asp-validation-for="SalarioBase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaIngreso" class="control-label"></label>
                <input asp-for="FechaIngreso" class="form-control" />
                <span asp-validation-for="FechaIngreso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NominaCRUD/Views/Empleadoes/Delete.cshtml
@model NominaCRUD.Models.Empleado

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>Seguro que desea eliminar esta informacion?</h3>
<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cedula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Departamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Departamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SalarioBase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SalarioBase)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaIngreso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaIngreso)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EmpleadoId" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Volver a la lista</a>
    </form>
</div>

NominaCRUD/Views/Empleadoes/Details.cshtml
@model NominaCRUD.Models.Empleado

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cedula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Departamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Departamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SalarioBase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SalarioBase)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaIngreso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaIngreso)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.EmpleadoId">Editar</a> |
    <a asp-action="Index">Volver a la lista</a>
</div>

NominaCRUD/Views/Empleadoes/Edit.cshtml
@model NominaCRUD.Models.Empleado

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar </h1>

<h4>Empleado</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EmpleadoId" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cedula" class="control-label"></label>
                <input asp-for="Cedula" class="form-control" />
                <span asp-validation-for="Cedula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Codigo" class="control-label"></label>
                <input asp-for="Codigo" class="form-control" />
                <span asp-validation-for="Codigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Departamento" class="control-label"></label>
                <input asp-for="Departamento" class="form-control" />
                <span asp-validation-for="Departamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SalarioBase" class="control-label"></label>
                <input asp-for="SalarioBase" class="form-control" />
                <span asp-validation-for="SalarioBase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaIngreso" class="control-label"></label>
                <input asp-for="FechaIngreso" class="form-control" />
                <span asp-validation-for="FechaIngreso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NominaCRUD/Views/Empleadoes/Index.cshtml
@model IEnumerable<NominaCRUD.Models.Empleado>

@{
    ViewData["Title"] = "Index";
}

<h1>Empleado</h1>

<p>
    <a asp-action="Create">Crear empleado</a>
</p>

<form asp-controller="Empleadoes" asp-action="Index">
    <p>
        Buscar: <input type="text" name="buscar" class="form-text">
        <input type="submit" value="Buscar" class="btn btn-sm btn-primary">
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cedula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Codigo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Departamento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SalarioBase)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaIngreso)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cedula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Codigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Departamento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SalarioBase)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaIngreso)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.EmpleadoId">Edtiar</a> |
                <a asp-action="Details" asp-route-id="@item.EmpleadoId">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.EmpleadoId">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>